### PR TITLE
fix: apply-action IE length should be variable to be backward-compatible with Release 15

### PR DESCRIPTION
**Pull request by tim-ywliu**
Let users specify apply-action IE length by themselves, ex: implementation with Release 15.

Note: it is an API breaking change:

NewApplyAction must provide multiple uint8 parameter instead of uint16.
ApplyAction return a byte slice instead of uint16.

### CODE REVIEW

**Comment by tim-ywliu** [comment]
@wmnsk 

Could you help review and merge this PR? We're waiting for using it.
Thanks.

**Review by wmnsk — COMMENTED** [review]
From what I understand the value could be 1 octet instead of 2 in the specific release. Could you add the test case for that then?

**Comment by tim-ywliu** [comment]
TS 29.244 R15.10

螢幕擷取畫面 2022-12-25 012330

**Comment by tim-ywliu** [comment]
@wmnsk 

The test case is added.

**Review by wmnsk — APPROVED** [review]
Ok looks good, thanks!
I’ll add a tag some time later

**Pull request merged**
