### PR TITLE
add UserPlaneIPResourceInformation array support in association setup response

### PR DESCRIPTION
**Pull request by TheWayYouMakeMeFeel**
This is a pr for adding array support for UserPlaneIPResourceInformation in association setup response only

### CODE REVIEW

**Review by wmnsk — APPROVED** [review]
Looks good. Thank you 😊

**Comment by krsna1729** [comment]
@wmnsk can we have a new release since behavior changed?

**Comment by wmnsk** [comment]
Done, with some additional changes (#57).

BTW, it seems you both refer to Release 15 (I assume so because UserPlaneIPResourceInformation is removed in Release 16), but do you have any reason not to move to Release 16?

For old releases, I will leave the existing codes and accept the changes as long as the codes for old/new releases can coexist without any hacky coding techniques. Otherwise, I'll drop/refuse the old ones.

**Comment by krsna1729** [comment]
Sounds good. Mostly because we are working control plane of that version. Recently I think it was removed? even with release 16 they had until the most recent minor version?

**Comment by wmnsk** [comment]
As far as I know, it's already been removed in V16.3.1(2020.04), but yes, the fact that I implemented it means it was still there in V16.x, as I started this project in 2019.11 when the first version of Release 16 was released 🙃 Please note that I won't come back to the older versions, anyway.

**Pull request merged**
